<?php
/**
 * @file
 * Sets up and handles changes to the availability form.
 */
 
 module_load_include('module', 'availability_week');
  
  /**
 * Implements hook_entity_info().
 */
function availability_entity_info(){
  // Set up the availablity and update entities
  $availability_info = array(
    'availability' => array(
      'label' => t('Availability Record'),
      'plural label' => t('Availability Records'),
      'description' => t('An entity type used for recording mediator availability.'),
      'entity class' => 'AvailabilityClass',
      'controller class' => 'EntityAPIController',
      'base table' => 'availability',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'vid',
      ),
      'label callback' => 'entity_class_label',
      'uri callback' => 'entity_class_uri',
      'bundles' => array(
	    'availability'=> array(
          'label' => 'Availability',
	    ),
	  ),
      
      'module' => 'availability',
      'views controller class' => 'EntityDefaultViewsController',
      'static cache' => TRUE,
      'view modes' => array(
        'full' => array(
          'label' => t('Full Availability'),
          'custom settings' =>  FALSE,
        ),
      ),
    ),
  );
  return $availability_info;
}

/**
 * Class for availability entity.
 */
class AvailabilityClass extends Entity {

  public function __construct(array $values = array(), $entityType = NULL) {
    parent::__construct($values, 'availability');
  }
}

/**
 * Custom Views Controller class to allow a change of field handler.
 */
class AvailabilityViewsController extends EntityDefaultViewsController {
  /*
    * Set the field handler of the start_date property to the data handler.
	* As start_date is an integer using UNIX timestamp format, the default handler
	* would be numeric. 
    */
  public function views_data() {
    $data = parent::views_data();
    $data['availability']['start_date']['field']['handler'] = 'views_handler_field_date';
	$data['availability']['field_availability_week']['field']['handler'] = 'views_handler_field_field';
    return $data;
  }
}

/**
 *  Implements hook_views_api to make Views api functions available
 */
function availability_views_api() {
  return array ('api' => 3);
}

function availability_views_post_execute(&$view) {
  if ($view->name == 'mediator_availability' || $view->name == 'availability_by_mediator') {
  	$periods = availability_periods_factory();
	$context = current_context_factory();
  	$aggregate = array();
	foreach ($context->availabilityCurrentWeeks() as $week_object) {
	  $week = $week_object->format('U');
	  foreach ($periods->availabilityDays() as $m_d => $m_days) {
	    foreach ($periods->availabilityTimes() as $m_t => $m_times) {
	  	  $aggregate[$week][$m_t.'_'.$m_d]['total'] = 0;
		  $aggregate[$week][$m_t.'_'.$m_d]['uids'] = array();
		}
	  }
	}
	foreach ($view->result as $seq => $record) {
	  $week = $record->availability_start_date;
	  if ($context->inRange($week)){
	    foreach ($record->field_field_availability_week as $delta => $week_part){
	      foreach ($periods->availabilityDays() as $m_d => $m_days) {
		    foreach ($periods->availabilityTimes() as $m_t => $m_times) {
	  	      if ($week_part['raw'][$m_t.'_'.$m_d] > 1) {
	  	        $aggregate[$week][$m_t.'_'.$m_d]['total'] ++;
			    $aggregate[$week][$m_t.'_'.$m_d]['uids'][$record->availability_uid] = $week_part['raw'][$m_t.'_'.$m_d];
			  }
	  	    }
	  	  }
		  $aggregate[$week]['notes'][$record->availability_uid] = $week_part['raw']['notes'];
	    }
	  }
	}
	$i=0;
	$sort_result = krsort ( $aggregate );
	$view->result = array();
	foreach (array_keys($aggregate) as $week) {
	  $view->result[$i] = new stdClass;
	  $view->result[$i]->availability_start_date = $week;
	  $view->result[$i]->field_field_availability_week[0]['rendered'] = 
	    drupal_get_form('availability_overview_table_' . $i, $i, $aggregate, $week);
	  $i++;
	}
  }
}

function availability_forms($form_id, $args) {
  $forms = array();
  if (!empty($args) && is_int($args[0]) && $form_id == 'availability_overview_table_' . $args[0]) {
    $forms[$form_id]['callback'] = 'availability_overview_table';
  }
  return $forms;
}

function availability_overview_table($form, &$form_state, $i, $aggregate, $week) {
  $periods = availability_periods_factory();
  $form['table_' . $i] = array(
    '#type' =>'container',
    '#prefix' => '<table>',
    '#suffix' => '</table>',
    'head' => array(
	  '#type' => 'container',
      '#prefix' => '<thead><tr>',
      '#suffix' => '</tr></thead>',
	),
	'body' => array(
	  '#type' => 'container',
      '#prefix' => '<tbody><tr>',
      '#suffix' => '</tr></tbody>',
	),
  );
  
  foreach ($aggregate[$week] as $slot => $value) {
  	if ($slot != 'notes'){
      $m_t = substr($slot, 0, 1);
      $m_d = substr($slot, 2, 2);
      $short_time = $periods->availabilityTimes('lo')[$m_t];
      $short_day = $periods->availabilityDays('lo')[$m_d];
      $day_number = $periods->availabilityDateCalc($week, $m_d);
	  $form['table_' . $i]['head'][$slot] = array(
	    '#markup' => 	$short_day . '<br/> ' . $day_number . '<br/>' . $short_time,
	    '#prefix' => '<th class = "availability-heading-cell">',
        '#suffix' => '</th>',
	  );
	  $form['table_' . $i]['body'][$slot] = array(
	    '#type' => 'submit',
	    '#value' => $value['total'],
	    '#name' => $week. '-' . $m_t . '-' . $m_d,
	    '#attributes' => array(
		  'class' => array('period-select-button'),
		),
	    '#ajax' => array(
		  'wrapper' => 'mediator-info',
		  'callback' => 'build_mediator_info',
		  'method' => 'replace',
		  'progress' => array(
		     'type' => 'throbber',
		     'message' => t(''),
		  ),
		),
	    '#submit' => array('availability_overview_submit'),
	    '#prefix' => '<td class = "availability-summary-cell">',
        '#suffix' => '</td>',
	  );
	}
  }
  $form_state['aggregate'] = $aggregate;
  return $form;
}

function availability_overview_submit($form, $form_state){
  
}

function build_mediator_info($form, $form_state){
  $selected_period = explode('-', $form_state['triggering_element']['#name']);
  $week = $selected_period[0];
  $time = $selected_period[1];
  $day =  $selected_period[2];
  $slot = $selected_period[1].'_'.$selected_period[2];
  $period_mediators = array();
  foreach ($form_state['aggregate'][$week][$slot]['uids'] as $uid => $availability) {
  	$period_mediators[$uid]['name'] = str_replace(' ' , '-', user_load($uid)->name);
	$period_mediators[$uid]['availability'] = $availability;
	$period_mediators[$uid]['notes'] = $form_state['aggregate'][$week]['notes'][$uid];
  }
  $meeting_commitments = new MeetingCommitments( NULL, $week, NULL);
  $period_commitments = $meeting_commitments->periodCommitments($week, $slot);
  $periods = availability_periods_factory();
  $date = $week + $periods->availabilityDays('num')[$day] * 24 * 60 * 60;
  $format_date = date('l jS F', $date);
  $time_of_day = $periods->availabilityTimes()[$time];
  $markup = '<div id="mediator-info" class="mediator-info-container">';
  $markup .= '<h2>Availabile Mediators</h2>';
  $markup .= '<div id="mediator-list">';
  $markup .= '<p>for the ' . $time_of_day . ' of ' . $format_date. ' </p>';
  if (!empty($period_mediators)) {
    foreach ($period_mediators as $uid => $details) {
  	  $availability = $details['availability'] == 3 ? 'yes' : 'maybe';
	  $slot = str_replace('_', '-', $slot);
  	  $markup .= '<div id = "box-' . $details['name'] .
  	    '" class = "mediator-name mediator-name-' . $availability . '">' .
  	    $details['name'] . '</div>';
    }
    $markup .= '</div><br/>';
    $markup .= '<div id="mediator-notes">';
    $markup .= '<div class = "availability-notes-title">Availability notes:</div>';
    foreach ($period_mediators as $uid => $details) {
  	  $notes = $details['notes'];
	  $class = $details['availability'] == 3 ? 'mediator-notes mediator-notes-yes' : 'mediator-notes mediator-notes-maybe';
  	  $markup .= '<div id = "notes-' . $details['name'] .
  	    '" class = "' . $class . '">' .
  	    $notes . '</div>';
	}
  }
  else {
  	$markup .= '<p>No mediators meet these criteria.</p>';
  }
  $markup .= '</div><br/><div id="mediator-meetings">';
  if (!empty($period_commitments)) {
  	$markup .= '<div class = "mediator-commitments-title">Existing commitments:</div>';
    foreach ($period_commitments as $commitment) {
  	  $date = strtotime($commitment['date']);
	  $format_date = date('l jS F \a\t H:i', $date);
  	  $title = $commitment['title'];
  	  $markup .= '<div id = "commitments-' . str_replace(' ' , '-', $commitment['name']) . 
  	    '" class = "mediator-commitments">' .
  	    $title . '<br/>' . $format_date . ' - ' . $commitment['duration'] . '</div>';
  	}
  }
  $markup .= '</div>';
  return array('#markup' => $markup);
}

/**
 * Implements hook_menu().
 */
function availability_menu(){
	
  $items = array();
  
  // Registers a path with menu item to the configuration settings for Availability
  $items['admin/config/content/availability'] = array(
    'title' => t('Availability settings'),
    'description' => t('Control the data displayed'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('availability_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/availability.admin.inc',
    'type' => MENU_NORMAL_ITEM, // optional
  );
 
  // Registers a path with menu item to call the availability form
  $items['availability'] = array(
    'description' => 'A form to record availability for mediation work.',
    'title' => 'My availability',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('availability_form'), //the name of the form here
    'access arguments' => array('record availability'),
  );

  // Registers a path with menu item for the Views availability reports
  $items['availability-reports'] = array(
    'title' => t('Availability reports'),
    'description' => t('Control the data displayed'),
    'page callback' => 'views_page', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('mediator_availability', 'page'), //the name of the form here
    'access arguments' => array('view availability'),
  );
  
  $items['availability-test'] = array(
    'title' => t('Test driver'),
    'description' => t('Run a test'),
    'page callback' => 'availability_test', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array(),
    'access arguments' => array('view availability'),
  );
  
  return $items;
}

/**
 * Helper function to get the mlid(s) pointing to a given path
 * @path: the path
 */
function _get_the_mlids($path) {
  $mlid = array();
  $menu_info = db_select('menu_links' , 'ml')
    ->condition('ml.link_path' , $path)
    ->fields('ml', array('mlid', 'plid'))
    ->execute()
    ->fetchAll();

  foreach($menu_info as $key => $value) {
    $mlid[] = $menu_info[$key]->mlid;
  }
  return $mlid;
}

/**
 * Implements hook_info.
 */ 
function availability_info() {
  return ('Welcome to the administration page for your availability records');
}
 
/**
 * Implements hook_permission().
 */
function availability_permission(){
  return array(
    'administer availability' =>  array(
      'title' => t('Administer availability'),
      'restrict access' => TRUE,
    ),
    'view availability' => array(
      'title' => t('View availability records'),
    ),
    'record availability' => array(
      'title' => t('Record own availability'),
    ),
  );
}

/**
 * Implements hook_form().
 */
function availability_form($form, &$form_state) {
	
  // A context object is created and held in $form_state until the form is cancelled.
  // This keeps track of the mediator and week we're currently dealing with.
  // By storing the object in the $form_state array we can just carry on where we left
  // off after the form is rebuilt.
  if (!isset($form_state['availability_context'])) {
    $context = current_context_factory();
    $form_state['availability_context'] = $context;
  }
  
  // Get the availability record for userid/start date 
  // The storage class does all the database handling for availability records
  // A storage object is instantiated with $context so it knows which record(s)
  // to load or save.
  $storage = availability_storage_factory($form_state['availability_context']);
  $entity = $storage->availabilityRetrieveEntity();
  $form_state['availability_current_entity'] = $entity;
  $items = field_get_items('availability', $entity, 'field_availability_week');
  
  $storage->availabilityHousekeeping();
     
  if(user_access('view availability')) {
	// auto-complete text box for office team to select a mediator
    // to update records on his/her behalf.  Mediator saved in the context variable. 
    $form['mediator'] = array(
      '#type' => 'textfield',
      '#title' => t('Mediator'),
      //'#prefix' => '<div id="availability_data_wrapper">',
      '#size' => 30,
      '#maxlength' => 60,
      '#autocomplete_path' => 'user/autocomplete',
      '#default_value' => $form_state['availability_context']->availabilityCurrentMediator()->name,
      '#weight' => '0',
    );
	// Submit button (using default callback function hook_form_submit)
    $form['select_mediator'] = array(
      '#type' => 'submit',
      '#value' => t('select mediator'),
      '#executes_submit_callback' => TRUE,
      '#validate' => array('validate_new_mediator'),
      '#submit' => array('select_new_mediator'),
      '#weight' => '2',
    );
  }
  
  // Prepare and display the mediator and period information
  $format = 'l jS F Y';
  $date_confirm = 'Availability for ' . $form_state['availability_context']->availabilityCurrentMediator()->name . 
    ' week commencing ' . date_format_date($form_state['availability_context']->availabilityCurrentMonday(), 'custom', $format);
  
  $form['week_commencing'] = array(
    '#markup' => '<h3>' . $date_confirm . '</h3>',
    '#prefix' => '<div class = "week-commencing-wrapper">',
    '#suffix' => '</div>',
    '#weight' => '4',
  );
  
  // Button to move to the previous week, calling function 'week_back'
  $form['earlier_monday'] = array(
    '#type' => 'submit',
    '#value' => t('previous week'),
    '#executes_submit_callback' => TRUE,
    '#submit' => array('week_back'),
    '#weight' => '6',
  );
  
  // Button to move to the next week, calling function 'week_forward
  $form['later_monday'] = array(
    '#type' => 'submit',
    '#value' => t('next week'),
    '#executes_submit_callback' => TRUE,
    '#submit' => array('week_forward'),
    '#weight' => '8',
  );
  
  
  // Insert availability data grid and notes as a field_availability_week widget
  if (!isset($form['#parents'])) {
  	$form['#parents'] = array();
  }
  $instance = field_info_instance('availability', 'field_availability_week', 'availability');
  $field = field_info_field_by_id($instance['field_id']);
  $form_element = field_default_form('availability', $entity, $field, $instance, 'und', $items, $form, $form_state);
  $form_element['field_availability_week']['#weight'] = '10';
  $form = array_merge_recursive($form_element, $form);
  
  // MeetingCommitments class handles meeting information. We use a MeetingCommitments object
  // to retrieve the meetings scheduled for the current mediator during the current week.
  $meeting_commitments = new MeetingCommitments(
    $form_state['availability_context']->availabilityCurrentMediator()->uid,
    $form_state['availability_context']->availabilityCurrentMonday()->format('U'),
    NULL
  );
  $meeting_list = $meeting_commitments->listCommitments();
  $meeting_string = '';
  if (strlen($meeting_list) > 0) {
    $meeting_string = '<h3>' . t('Meeting information:') . '</h3> ' .
	  $meeting_list ;
  }
  
  // The meeting information is placed as a markup element in a container created as part of the
  // field_availability_week widget	
  $form['field_availability_week']['und'][0]['meetings_container']['meetings_markup'] = array(
    '#type' => 'markup',
    '#markup' => $meeting_string,
  );
   
  // Checkbox control for repeating weeks
  $form['repeat_wrapper'] = array(
     '#type' => 'container',
	 '#attributes' => array(
       'class' => array('repeat-group', 'text-vertical-1'),
	 ),
	 '#weight' => '12',
	 'repeat_week' => array(
       '#title' => 'Repeat for another ',
       '#type' => 'checkbox',
       '#default_value' => FALSE,
     ),
   );
   
   // Spinner control for number of repeating weeks
   $form['repeat_number_wrapper'] = array(
     '#type' => 'container',
     '#weight' => '14',
	 '#attributes' => array(
       'class' => array('repeat-group'),
	 ),
	 'number_weeks' => array(
       '#title' => '',
       '#type' => 'textfield',
       '#default_value' => 0,
       '#size' => 5,
       '#attributes' => array('id' => 'edit-number-weeks'),
       '#attached' => array(
         'library' => array(
           array('system', 'ui.widget'),
         ),
         'js' => array(
           drupal_get_path('module', 'availability') . '/scripts/spinner.js',
           drupal_get_path('module', 'availability') . '/scripts/my_availability.js',
         ),
       ),
     ),
   );
   
  // Text to help make repeating weeks controls make sense
   $form['repeat_label_wrapper'] = array(
     '#type' => 'container',
     '#weight' => '16',
	 '#attributes' => array(
       'class' => array('repeat-group', 'text-vertical-2'),
	 ),
	 'number_label' => array(
       '#type' => 'markup',
       '#markup' => '<p> weeks </p>',
     ),
   );
   
  // Submit button calling default callback function availability_form_submit
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Save the week'),
    '#prefix' => '<div class="availability-submit">',
    '#weight' => '18',
  );
  
  // Cancel button, calling function 'form_cancel'
  $form['cancel_button'] = array(
    '#type' => 'submit',
    '#value' => t('Cancel'),
    '#suffix' => '</div>',
    '#submit' => array('form_cancel'),
    '#weight' => '20',
  );
  $form['#attached']['css'] = array(
    drupal_get_path('module', 'availability') . '/availability.css',
  );
  return $form;
}

/**
 * Implements hook_form_validate().
 */
function availability_form_validate($form, &$form_state) {
  
}

/**
 * Implements hook_form_submit().
 */
function availability_form_submit($form, &$form_state) {
  // Instantiate a storage object with the current context object 
  $storage = availability_storage_factory($form_state['availability_context']);
    if ($form_state['values']['repeat_week'] 
    && isset($form_state['values']['number_weeks']) 
    && $form_state['values']['number_weeks'] > 0) {
  	// Request to save same availability pattern for the current week plus
  	// additional weeks
  	$repeat_weeks = $form_state['values']['number_weeks'];
	$report = $storage->availabilitySaveEntity($form, $form_state, $repeat_weeks);
  }
  else {
  	// Request to save availability pattern just for the current week
  	$repeat_weeks = 0;
    $report = $storage->availabilitySaveEntity($form, $form_state);
  }
  
  $monday = $form_state['availability_context']->availabilityCurrentMonday();
  if (count(array_filter($report)) == $repeat_weeks + 1 ) {
  	// If all requested weeks saved successfully, confirm to user.
  	$msg = 'Thank you. ' . count($report) . ((count($report)>1)?' weeks':' week') .
  	  ' successfully saved commencing ' . $monday->format('l jS F');
  	drupal_set_message($msg , $type = 'status');
  }
  else {
  	// If any failed give the user a report
  	$msg = t('We had a problem saving your record(s). ' .  count($report).
  	 ((count(array_filter($report))>1)?' weeks':' week') . 'were saved out of ' . $repeat_weeks + 1 . 
  	 ' requested commencing ' . $monday->format('l jS F'). '.  Please contact the office.');
  	drupal_set_message($msg , $type = 'error');
  }
  unset($form_state['input']['field_availability_week']);
  unset($form_state['input']['repeat_week']);
  unset($form_state['input']['number_weeks']);
  $form_state['rebuild'] = TRUE;
}

/**
 * Validation handler for new mediator name
 *
 */ 
function validate_new_mediator($form, &$form_state){
  if (!user_load_by_name($form_state['values']['mediator']) || !is_object(user_load_by_name($form_state['values']['mediator']))) {
	form_set_error('mediator', 'Enter a valid user name.');
  }
  else {
    if (!in_array('mediator', user_load_by_name($form_state['values']['mediator'])->roles)) {
	  form_set_error('mediator', "This user is not a mediator.");
	}
  }
}

/**
 * Submit handler for new mediator name
 * 
 */ 
function select_new_mediator($form, &$form_state) {
  $mediator = user_load_by_name($form_state['values']['mediator']);
  $form_state['availability_context']->setCurrentMediator($mediator);
  $form_state['rebuild'] = TRUE;
  unset($form_state['input']['field_availability_week']);
  unset($form_state['input']['repeat_week']);
  unset($form_state['input']['number_weeks']);
}

/**
 * Button handler to implement moving to next week.
 * provided we haven't gone further ahead than the upper limit
 */ 
function week_forward($form, &$form_state) {
  $result = $form_state['availability_context']->nextMonday();
  if (!$result) {
	drupal_set_message(t('This is as far ahead as we record.') , $type = 'status');
  } 
  $form_state['rebuild'] = TRUE;
  unset($form_state['input']['field_availability_week']);
  unset($form_state['input']['repeat_week']);
  unset($form_state['input']['number_weeks']);
}

/**
 * Button handler to implement moving to previous week.
 * provided we haven't gone further back than the lower limit
 */
function week_back($form, &$form_state) {
  $result = $form_state['availability_context']->previousMonday();
  if (!$result) {
	drupal_set_message(t('This is the earliest you can update.') , $type = 'status');
  } 
  $form_state['rebuild'] = TRUE;
  unset($form_state['input']['field_availability_week']);
  unset($form_state['input']['repeat_week']);
  unset($form_state['input']['number_weeks']);
}

function form_cancel($form, &$form_state){
	unset ($form_state['availability_context']);
	$form_state['rebuild'] = FALSE;
	$form_state['redirect'] = 'node';
}

/**
 * Implements hook_block_info to introduce the block 
 */ 
function availability_block_info() {
  $blocks['mediators'] = array (
    'info' => t('Available mediators'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
    'weight' => 20,
  );
  return $blocks;
}

/**
 * Implements hook_block_view to set up the list of mediators available at a given period on a given day 
 */ 
function availability_block_view($delta = '') {
  switch ($delta) {
    case 'mediators':
	  $block = array();
	  $block['content'] = array(
	    'mediator-list' => array(
	      '#type' => 'container',
	      '#attributes' => array(
		    'class' => array('mediator-info-container'),
		    'id' => 'mediator-info',
		  ),
		),
	  );
	  drupal_add_js(drupal_get_path('module', 'availability') . '/scripts/mediator_info.js');
	  drupal_add_css(drupal_get_path('module', 'availability') . '/availability.css');
	  $scripts = drupal_get_js();
      $vars['scripts'] = $scripts;
	return $block;
  }
}

/**
 *  Implements hook_cron to carry out scheduled tasks.  Specifically maintaining the table that tracks mediator
 *  updates and deleting availability records older than the "delete week" criterion.  Also sending out emails
 *  to all mediators prompting them to update their availability for the week after next if it's the designated
 *  day of the week and the job hasn't been done in the last three days.  If all emails are sent successfully by
 *  the drupal_mail function then availability_last_email is updated in the array of persistent variables. 
 *   
 */
function availability_cron() {
  $context = current_context_factory();
  $storage = availability_storage_factory($context);
  $storage->availabilityHousekeeping();
}

/**
 *  Implements hook_mail to send out reminder email using the user specified template in the admin form.
 *  @params: $params includes the mediator's name, start date for the week and the link to navigate to the site
 */
function availability_mail($key, &$message, $params) {
  $availability_settings= variable_get("availability_settings", array());
  if ($key = 'weekly_reminder') {
  	
	$subject = $availability_settings['availability_email_subject'];
	$subject = str_replace('[week_commencing]', $params['week_start_date'], $subject);
	$subject = str_replace('[site_link]', '<a href=' .$params['web_link'] . '> '. $params['web_link'] . '</a>', $subject);
	
	$body = $availability_settings['availability_email_body'];
	$body = str_replace('[week_commencing]', $params['week_start_date'], $body);
	$body = str_replace('[site_link]', '<a href=' .$params['web_link'] . '> '. $params['web_link'] . '</a>', $body);
	$body_lines = explode('%/', preg_replace('/\r?\n|\r/','%/', $body));
	for ($i = 0 ; $i < sizeof($body_lines) ; $i++) {
	  $body_lines[$i] = '<p> ' . $body_lines[$i] . ' </p>';
	}
    $message['subject'] = $subject;
    $message['body'] = $body_lines;
  }
}

/**
 *  Set up the select box for the exposed filter for the missing updates form.
 *  First set up an associative array of Mondays covered by the report with key full ISO date format
 *  and value abbreviated date.  These are used in descending order to populated the exposed select list control
 *  to choose the week for the report.
 *  
 */
function availability_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "views_exposed_form" && ($form['#id'] == "views-exposed-form-missing-updates-page"  || $form['#id'] == "views-exposed-form-updates-provided-page")) {
	$context = current_context_factory();
	$mondays = $context->availabilityCurrentWeeks();
	// Change the date objects in the Mondays array to timestamps so they can be sorted
	array_walk ( $mondays , function(&$value,$key){
	  $value = $value->format('U');
	});
	rsort($mondays);
	// Change the format again to readable date and set up an options array for the select 
	// control with a more complete date in the key as this is the one that gets used for the query.
	$options = array();
	foreach ($mondays as $monday) {
	  $value_monday = date('jS F', $monday);
	  $key_monday = date('jS F Y', $monday);
      $options[$key_monday] = $value_monday;
	}
	// Re-write the exposed date control as a select select control
    $form['start_date']['#type'] = "select";
    $form['start_date']['#size'] = null;
    $form['start_date']['#options'] = $options;
	if (empty($_GET['start_date'])) {
      $form_state['input']['start_date'] = key($options);
    }
  }
}

/**
* Functions for indirect instantiation of classes
* @return: a new instance of the corresponding class  
*/	 

function meeting_commitments_factory() {
  $meetings = new MeetingCommitments;
  return $meetings;
}

function current_context_factory() {
  $context = new AvailabilityContext();
  return $context;
}

function availability_storage_factory($context) {
  return new AvailabilityStorage($context);
}

function availability_test() {
	return array();
}



